# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

definition_beta <- function(X, Y, tau, omega_vect, computation_norm, Proc_Time, thres, non_zeros_pred, lambda_H_start, lambda_K_start, ratio_lambda_H, num_lambda_H, verbose, sum_cpp) {
    .Call(`_AFSSEN_definition_beta`, X, Y, tau, omega_vect, computation_norm, Proc_Time, thres, non_zeros_pred, lambda_H_start, lambda_K_start, ratio_lambda_H, num_lambda_H, verbose, sum_cpp)
}

definition_beta_CV <- function(X_train, Y_train, X_test, Y_test, tau, omega_vect, computation_norm, Proc_Time, thres, non_zeros_pred, lambda_H_start, lambda_K_start, ratio_lambda_H, num_lambda_H, early_CV, early_CV_thres, max_ite, target_inc, verbose, sum_cpp) {
    .Call(`_AFSSEN_definition_beta_CV`, X_train, Y_train, X_test, Y_test, tau, omega_vect, computation_norm, Proc_Time, thres, non_zeros_pred, lambda_H_start, lambda_K_start, ratio_lambda_H, num_lambda_H, early_CV, early_CV_thres, max_ite, target_inc, verbose, sum_cpp)
}

